[package]
name = "fin_iex"
version = "0.1.0"
authors = ["Simon Johnston <johnstonskj@gmail.com>"]
edition = "2018"

[dependencies]
fin_model = { path = "../fin_model" }

chrono = "0.4.7"
steel-cent = "0.2.2"
reqwest = "0.9.18"

log = { version = "0.4", features = ["std"] }
flexi_logger = { version = "^0.13.2", features = ["colors", "specfile", "ziplogs"] }
