language: rust
sudo: false
cache: cargo

rust:
  - stable
  - beta
  - 1.34.0
  - nightly

os:
  - linux
  - osx
  - windows

env:
  global:
    - RUST_BACKTRACE=1

matrix:
  fast_finish: true
  allow_failures:
    - rust: nightly

  include:
    - name: format
      rust: stable
      before_script:
        - rustup component add rustfmt
      script:
        - cargo fmt --all -- --check

    - name: style
      rust: stable
      install:
      - rustup component add clippy
      script:
      - cargo clippy --all -- -D warnings

script:
  - cargo build --verbose --all
  - cargo test  --verbose --all
  - cargo doc   --verbose --package fin_model --no-deps
#   cargo coveralls --verbose
#   cargo doc-upload --verbose
#   cargo package --verbose --manifest-path fin_model/Cargo.toml
#   cargo package --verbose --manifest-path fin_data/Cargo.toml
#   cargo package --verbose --manifest-path fin_iex/Cargo.toml

branches:
  only:
    - master
    - auto

notifications:
  email:
    on_success: never
