language: rust
sudo: false

rust:
  - stable
  - beta
  - nightly

os:
  - linux
  - osx
#  - windows

matrix:
  fast_finish: true
  allow_failures:
    - rust: nightly

script:
  - cargo build --verbose --all
  - cargo test --verbose --all

#script: |
#  cargo build --verbose --all-features &&
#  cargo test  --verbose --all-features &&
#  cargo test  --verbose --release --all-features &&
#  cargo doc   --verbose -p fin_model --all-features --no-deps &&
#  cargo doc   --verbose -p fin_data  --all-features --no-deps &&
#  cargo doc   --verbose -p fin_iex   --all-features --no-deps &&
#  cargo coveralls --verbose
#  cargo doc-upload

env:
  global:
    - RUST_BACKTRACE=1

branches:
  only:
    - master
    - auto

notifications:
  email:
    on_success: never
