language: rust
cache: cargo
sudo: false

rust:
  - 1.0.0
  - stable
  - beta
  - nightly

os:
  - linux
  - osx

matrix:
  fast_finish: true
  allow_failures:
    - rust: nightly


script: |
  cargo build --verbose &&
  cargo test  --verbose &&
  cargo doc   --verbose
#  cargo coveralls --verbose
#  cargo doc-upload

branches:
  only:
    - master
    - auto

notifications:
  email:
    on_success: never
