language: rust
sudo: false
cache: cargo

rust:
  - stable
  - beta
  - 1.31.0 # 2018!
  - nightly

os:
  - linux
  - osx
  - windows

env:
  global:
    - RUST_BACKTRACE=1

matrix:
  fast_finish: true
  allow_failures:
    - rust: nightly
  include:
    - name: "rustfmt"
      rust: stable
      before_script:
        - rustup component add rustfmt
      script:
        - cargo fmt --all -- --check

script: |
  cargo build --verbose --all &&
  cargo test  --verbose --all &&
  cargo doc   --verbose --package fin_model --no-deps

#script: |
#  cargo build --verbose --all-features &&
#  cargo test  --verbose --all-features &&
#  cargo test  --verbose --release --all-features &&
#  cargo coveralls --verbose
#  cargo doc-upload

branches:
  only:
    - master
    - auto

notifications:
  email:
    on_success: never
