language: rust
cache: cargo
sudo: false

rust:
  - stable
  - beta
before_script:
  - rustup component add clippy
  - rustup component add rustfmt
script:
  - cargo fmt --all -- --check
  - cargo clippy
#  - cargo clippy --all-targets --all-features -- -D warnings
  - cargo build
  - cargo test

rust:
  - nightly
before_script:
   - rustup component add clippy --toolchain=nightly || cargo install --git https://github.com/rust-lang/rust-clippy/ --force clippy
script:
  - cargo build
  - cargo test

os:
  - linux
  - osx

matrix:
  allow_failures:
    - rust: nightly
